version: "3.9"
services:
  elasticsearch:
    container_name: elasticsearch_container
    image: elasticsearch:${ES_VERSION:-8.4.2}
    networks:
      - imdhemy-es
    ports:
      - "${ES_PORT:-9200}:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - es-disk:/usr/share/elasticsearch/data
  kibana:
    container_name: kibana_container
    image: kibana:${ES_VERSION:-8.4.2}
    networks:
      - imdhemy-es
    ports:
      - "${KIBANA_PORT:-5601}:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
volumes:
  es-disk:
    driver: local
networks:
  imdhemy-es:
